# These are supported funding model platforms

github: [yangKJ]
buy_me_a_coffee: yangkj3102
custom: ["https://raw.githubusercontent.com/yangKJ/Harbeth/master/Screenshot/WechatIMG2.jpg", "https://raw.githubusercontent.com/yangKJ/Harbeth/master/Screenshot/WechatIMG1.jpg"]
